# Generated by Django 6.0.8 on 2026-08-13 20:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('start_url', models.URLField(max_length=2048)),
                ('allowed_domains', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=16)),
                ('respect_robots', models.BooleanField(default=True)),
                ('render_javascript', models.BooleanField(default=False)),
                ('max_pages', models.PositiveIntegerField(default=5000, validators=[django.core.validators.MaxValueValidator(1000000)])),
                ('max_depth', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(50)])),
                ('request_delay_ms', models.PositiveIntegerField(default=750, validators=[django.core.validators.MaxValueValidator(120000)])),
                ('concurrency', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)])),
                ('spend_cap', models.DecimalField(decimal_places=2, default=12, max_digits=10)),
                ('extraction_schema', models.JSONField(blank=True, default=dict)),
                ('custom_headers', models.JSONField(blank=True, default=dict)),
                ('schedule', models.CharField(blank=True, help_text='Optional cron expression', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('budget_stopped', 'Budget stopped')], db_index=True, default='queued', max_length=24)),
                ('pages_visited', models.PositiveIntegerField(default=0)),
                ('pages_stored', models.PositiveIntegerField(default=0)),
                ('failed_requests', models.PositiveIntegerField(default=0)),
                ('blocked_requests', models.PositiveIntegerField(default=0)),
                ('duplicate_pages', models.PositiveIntegerField(default=0)),
                ('bytes_downloaded', models.PositiveBigIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('extraction_health', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='crawler.crawlproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=12)),
                ('code', models.CharField(db_index=True, max_length=80)),
                ('message', models.CharField(max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crawler.crawlrun')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionFieldMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=180)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('values_found', models.PositiveIntegerField(default=0)),
                ('health_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('drift_detected', models.BooleanField(default=False)),
                ('sample_values', models.JSONField(blank=True, default=list)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_metrics', to='crawler.crawlrun')),
            ],
            options={
                'ordering': ['health_score', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
                ('final_url', models.URLField(max_length=2048)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=160)),
                ('text_content', models.TextField(blank=True)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('extractor_version', models.CharField(default='1.0', max_length=32)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='crawler.crawlrun')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='crawlproject',
            index=models.Index(fields=['owner', 'status'], name='project_owner_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='crawlproject',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_project_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='crawlrun',
            index=models.Index(fields=['project', '-created_at'], name='run_project_created_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlrun',
            index=models.Index(fields=['status', '-created_at'], name='run_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlevent',
            index=models.Index(fields=['run', '-occurred_at'], name='event_run_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractionfieldmetric',
            constraint=models.UniqueConstraint(fields=('run', 'field_name'), name='unique_metric_per_run_field'),
        ),
        migrations.AddIndex(
            model_name='scrapedpage',
            index=models.Index(fields=['run', 'status_code'], name='page_run_status_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedpage',
            index=models.Index(fields=['run', 'content_hash'], name='page_run_hash_idx'),
        ),
        migrations.AddConstraint(
            model_name='scrapedpage',
            constraint=models.UniqueConstraint(fields=('run', 'url'), name='unique_url_per_run'),
        ),
    ]
